---

# == Notes ==

# GitLab automatically passes artifacts from previous stages by default

# This CI definition uses a GitLab provided include template

# Secret variables
# - Set required secret variables at: https://gitlab.data.bas.ac.uk/MAGIC/magic-projects-portfolio/-/settings/ci_cd
# - Variables are grouped by section in KEY: "value" format (e.g. FOO: "bar")
#   Sensitive values are represented by "[Sensitive]"
#
# - DigitalOcean
#   > DIGITALOCEAN_ACCESS_TOKEN: "[Sensitive]"

# == Includes ==

include:
  - template: 'Workflows/MergeRequest-Pipelines.gitlab-ci.yml'

# == Global settings ==

stages:
  - 💥 setup
  - 🧪 test
  - 📦 package
  - 🚀 deploy

image:
  name: python:3.8-slim
  entrypoint: [""]

variables:
  DO_APP_PLATFORM_APP_ID: 13a185b6-5d92-4d65-b773-cc8190b0637c

# == Jobs ==

setup:
  stage: 💥 setup
  before_script:
    - python -m pip install --upgrade pip
    - python -m pip install poetry==1.1.4
    - poetry config virtualenvs.in-project true
  script:
    - poetry install
  artifacts:
    paths:
      - .venv
    expire_in: 1 week
    when: always

test:
  stage: 🧪 test
  before_script:
    - python -m pip install --upgrade pip
    - python -m pip install poetry==1.1.4
    - poetry config virtualenvs.in-project true
    - poetry export --dev --format=requirements.txt --without-hashes --output requirements-safety.txt
  script:
    - poetry run safety check --file requirements-safety.txt
    - poetry run flake8 src tests
  needs:
    - job: setup
      artifacts: true

package:
  stage: 📦 package
  before_script:
    - python -m pip install --upgrade pip
    - python -m pip install poetry==1.1.4
    - poetry config virtualenvs.in-project true
  script:
    - poetry publish --build --repository bas-gitlab --username gitlab-ci-token --password ${CI_JOB_TOKEN}
  needs:
    - job: test
    - job: setup
      artifacts: true
#  rules:
#    - if: '$CI_COMMIT_TAG != null'

deploy:
  stage: 🚀 deploy
  image:
    name: digitalocean/doctl:1-latest
    entrypoint: [ "" ]
  script:
    - /app/doctl apps create-deployment $DO_APP_PLATFORM_APP_ID --force-rebuild
  needs:
    - job: package
#  rules:
#    - if: '$CI_COMMIT_TAG != null'
