services:
  terraform:
    image: hashicorp/terraform:0.14.8
    entrypoint: ash
    working_dir: /workspace
    volumes:
      - ./:/workspace/
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - DIGITALOCEAN_TOKEN
      - GITLAB_TOKEN=${GITLAB_DOT_COM_GITLAB_TOKEN}
