services:
  terraform:
    # local image is workaround for requested docker tag not yet existing on DockerHub
    build: .
    image: zenika/terraform-azure-cli:release-6.1_terraform-0.15.5_azcli-2.28.1
    entrypoint: bash
    working_dir: /workspace
    volumes:
      - ./:/workspace/
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - DIGITALOCEAN_TOKEN
      - GITLAB_TOKEN=${GITLAB_DOT_COM_GITLAB_TOKEN}
